name: Deploy to Azure Kubernetes Service

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main  # change if your main branch is different

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Login to Azure using service principal
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Login to Azure Container Registry
      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} .

      # Step 5: Push Docker image to ACR
      - name: Push Docker image
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

      # Step 6: Get AKS credentials
      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing

      # Step 7: Deploy to AKS
      - name: Deploy to AKS
        run: |
          # Replace these names with your actual deployment & container names if different
          kubectl set image deployment/neighbor-deployment neighbor-container=$ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}
          kubectl rollout status deployment/neighbor-deployment
